# https://taskfile.dev

version: '3'

tasks:
  cluster:up:
    desc: "Start FalkorDB cluster"
    cmds:
      - docker-compose -f docker-compose.cluster.yml up -d
  cluster:down:
    desc: "Stop FalkorDB cluster"
    cmds:
      - docker-compose -f docker-compose.cluster.yml down -v
  standalone:up:
    desc: "Start FalkorDB standalone"
    cmds:
      - docker-compose -f docker-compose.standalone.yml up -d
  standalone:down:
    desc: "Stop FalkorDB standalone"
    cmds:
      - docker-compose -f docker-compose.standalone.yml down -v

  test:standalone:
    desc: "Run tests against standalone FalkorDB"
    cmds:
      - task: standalone:up
      - defer: task standalone:down
      - FALKORDB_ADDR=0.0.0.0:9379 FALKORDB_TEST_MODE=standalone go test -v ./...
      
  test:cluster:
    desc: "Run tests against FalkorDB cluster"
    cmds:
      - task: cluster:up
      - defer: task cluster:down
      - sleep 5
      - FALKORDB_ADDR=0.0.0.0:9379 FALKORDB_TEST_MODE=cluster go test -v ./...

  test:
    desc: "Run all tests"
    cmds:
      - task: test:standalone
      - task: test:cluster