# https://taskfile.dev

version: '3'

tasks:
  cluster:up:
    desc: "Start FalkorDB cluster"
    cmds:
      - docker-compose -f docker-compose.cluster.yml up -d
  cluster:down:
    desc: "Stop FalkorDB cluster"
    cmds:
      - docker-compose -f docker-compose.cluster.yml down -v
  standalone:up:
    desc: "Start FalkorDB standalone"
    cmds:
      - docker-compose -f docker-compose.standalone.yml up -d
  standalone:down:
    desc: "Stop FalkorDB standalone"
    cmds:
      - docker-compose -f docker-compose.standalone.yml down -v